import type { ErdEdge, ErdNode, ErdTableNode } from "../types/erd"
import { isTableNode } from "./node-guards"

type ForeignKey = {
  sourceTable: string
  sourceColumn: string
  targetTable: string
  targetColumn: string
}

const stripHandleSide = (handle: string): string =>
  handle.replace(/-(left|right|top|bottom)$/, "")

/**
 * Plain SQL for handing to a database. Unlike buildSQL this drops the layout
 * directives and inlines the foreign keys into the CREATE TABLE body, so the
 * result reads like a schema someone wrote by hand.
 */
export const exportToSQL = (nodes: ErdNode[], edges: ErdEdge[]): string => {
  const tableNodes = nodes.filter(isTableNode)
  const tablesById = new Map<string, ErdTableNode>(
    tableNodes.map((node) => [node.id, node])
  )

  let sql = `-- Generated by ERD Builder
-- Date: ${new Date().toISOString()}
-- Tables: ${tableNodes.length}
-- Relationships: ${edges.length}

`

  const foreignKeys = new Map<string, ForeignKey[]>()

  edges.forEach((edge) => {
    const sourceNode = tablesById.get(edge.source)
    const targetNode = tablesById.get(edge.target)

    if (sourceNode && targetNode && edge.sourceHandle && edge.targetHandle) {
      const sourceColumn = sourceNode.data.columns.find(
        (c) => c.id === stripHandleSide(edge.sourceHandle!)
      )
      const targetColumn = targetNode.data.columns.find(
        (c) => c.id === stripHandleSide(edge.targetHandle!)
      )

      if (sourceColumn && targetColumn) {
        const existing = foreignKeys.get(edge.target) ?? []
        existing.push({
          sourceTable: sourceNode.data.name,
          sourceColumn: sourceColumn.name,
          targetTable: targetNode.data.name,
          targetColumn: targetColumn.name,
        })
        foreignKeys.set(edge.target, existing)
      }
    }
  })

  tableNodes.forEach((node) => {
    const table = node.data
    sql += `-- Table: ${table.schema}.${table.name}\n`
    sql += `CREATE TABLE ${table.schema}.${table.name} (\n`

    const columnDefinitions: string[] = []

    table.columns.forEach((column) => {
      let columnDef = `    ${column.name} ${column.format.toUpperCase()}`

      if (!column.isNullable) {
        columnDef += " NOT NULL"
      }

      if (column.isIdentity) {
        if (column.format === "integer" || column.format === "bigint") {
          columnDef += " GENERATED ALWAYS AS IDENTITY"
        }
      }

      if (column.isUnique && !column.isPrimary) {
        columnDef += " UNIQUE"
      }

      columnDefinitions.push(columnDef)
    })

    const primaryKeys = table.columns
      .filter((c) => c.isPrimary)
      .map((c) => c.name)
    if (primaryKeys.length > 0) {
      columnDefinitions.push(`    PRIMARY KEY (${primaryKeys.join(", ")})`)
    }

    const tableFKs = foreignKeys.get(node.id) ?? []
    tableFKs.forEach((fk) => {
      columnDefinitions.push(
        `    FOREIGN KEY (${fk.targetColumn}) REFERENCES ${table.schema}.${fk.sourceTable}(${fk.sourceColumn})`
      )
    })

    sql += columnDefinitions.join(",\n")
    sql += "\n);\n\n"

    if (table.indexes && table.indexes.length > 0) {
      table.indexes.forEach((index) => {
        sql += `CREATE INDEX ${index.name} ON ${table.schema}.${table.name} USING ${index.type.toUpperCase()} (${index.columns.join(", ")});\n`
      })
      sql += "\n"
    }
  })

  if (edges.length > 0) {
    sql += `-- Relationships Summary:\n`
    edges.forEach((edge) => {
      const sourceNode = tablesById.get(edge.source)
      const targetNode = tablesById.get(edge.target)
      if (sourceNode && targetNode) {
        sql += `-- ${sourceNode.data.name} -> ${targetNode.data.name}\n`
      }
    })
    sql += "\n"
  }

  return sql
}
